console.log("BEFORE ALL")

// BLACK & WHITE
const BLACK_COLOR = "#000000";
const WHITE_COLOR = "#FFFFFF";
// GREYS
const GREY_COLOR = "#4A4A4A";
const VERY_LIGHT_GREY_COLOR = "#F9F9F9";
const LIGHT_GREY_COLOR = "#8C8C8C";

// BLUE
const BLUE_COLOR = "#6786D3";
const DARK_BLUE_COLOR = "#4F6DB8";

// RED
const RED_ERROR_COLOR = "#FF5757";
const DARK_RED_ERROR_COLOR = "#E34A4A";

export {
  GREY_COLOR,
  BLACK_COLOR,
  WHITE_COLOR,
  VERY_LIGHT_GREY_COLOR,
  BLUE_COLOR,
  LIGHT_GREY_COLOR,
  DARK_BLUE_COLOR,
  RED_ERROR_COLOR,
  DARK_RED_ERROR_COLOR,
};
