const BLACK_COLOR = "#000000";
const GREY_COLOR = "#4A4A4A";
const LIGHT_FREY_COLOR = "#F9F9F9";
const BLUE_COLOR = "#6786D3";

export { GREY_COLOR, BLACK_COLOR, LIGHT_FREY_COLOR, BLUE_COLOR };
